apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: default-pvc
    namespace: final
spec:
    accessModes:
        -  ReadWriteOnce
    storageClassName: gp2
    resources:
        requests:
            storage: 2Gi
    volumeMode: Filesystem